### PR TITLE
Add option to collect logs in hub cluster

### PR DESCRIPTION
**Pull request by OdedViner**
Tested with my image:
```
oc adm must-gather --image=quay.io/oviner/ocs-must-gather:dr_hub_mg -- /usr/bin/gather -d
```
```
$ pwd
/home/oviner/ClusterPath/auth/dr_mg
$ ls
openshift-operators
```

### CODE REVIEW

**Comment by yati1998** [comment]
LGTM, would want someone from DR team to review it too.

**Review by prsurve — APPROVED** [review]

**Pull request merged**
