### PR TITLE
Syncing latest changes from main for odf-must-gather

### PR DESCRIPTION
**Pull request by df-build-team**
PR containing the latest commits from main branch

### CODE REVIEW

**Comment by black-dragon74** [comment]
Hi @nixpanic, the CI for release branches is not working (and I'm taking care of that as we speak). You can add the labels manually until we have proper pipelines in place.

Regards

**Comment by black-dragon74** [comment]
> @black-dragon74 any ETA for the fix? The merge seems to be blocked for over a month now :/

The fix PR for the CI is already there in Openshift release repo https://github.com/openshift/release/pull/44274

This PR needs to be merged after manual review, once and then the CI will work as expected. The reason for this not working in its current state is because the CI (for the main branch) was merely a placeholder before.

As soon as this PR is merged, We need to merge the one in OpenShift release repo.

Regards

**Comment by Nikhil-Ladha** [comment]
> > @black-dragon74 any ETA for the fix? The merge seems to be blocked for over a month now :/
> 
> The fix PR for the CI is already there in Openshift release repo [openshift/release#44274](https://github.com/openshift/release/pull/44274)
> 
> This PR needs to be merged after manual review, once and then the CI will work as expected. The reason for this not working in its current state is because the CI (for the main branch) was merely a placeholder before.
> 
> As soon as this PR is merged, We need to merge the one in OpenShift release repo.
> 
> Regards

In that case, I am not sure what `manual` review is needed here.
I believe, we should be good to override the tests and merge this PR.
@red-hat-storage/must-gather can we get that done here?

**Comment by black-dragon74** [comment]
@Nikhil-Ladha None actually as all PRs have been reviewed on the main branch anyways. Someone with write access needs to merge this PR. 

/cc: @yati1998

**Pull request merged**
