### PR TITLE
segregate odf collection from default

### PR DESCRIPTION
**Pull request by yati1998**
Currently the default and odf mode collects all the resouces. This commit segregates the odf mode
from default mode.

### CODE REVIEW

**Comment by yati1998** [comment]
@black-dragon74 please re-review the PR, I have tested it, It works fine now

**Comment by black-dragon74** [comment]
> @black-dragon74 please re-review the PR, I have tested it, It works fine now

You do not need to pass base_collection_path to any of the subscripts. 

Just `<script> &` will do

**Comment by yati1998** [comment]
@black-dragon74 please do reviw the PR again

**Review by black-dragon74 — APPROVED** [review]
LGTM

**Pull request merged**
