### PR TITLE
Add the command to fetch Ceph's health history.

### PR DESCRIPTION
**Pull request by ashishkumsingh**
Add the command to fetch Ceph's health history.

### CODE REVIEW

**Comment by black-dragon74** [comment]
LGTM

**Review by yati1998 — APPROVED** [review]

**Comment by yati1998** [comment]
@ashishkumsingh can you please check the merge conflicts

**Comment by black-dragon74** [comment]
@ashishkumsingh Can you please rebase?

**Comment by black-dragon74** [comment]
Rebased and handled at: #132

**Pull request closed without merging**
